openbox: fix debian undefined reference to symbol 'XSyncIntToValue'
  CCLD     openbox/openbox
/usr/bin/ld: openbox/openbox-client.o: undefined reference to symbol 'XSyncIntToValue'
/usr/bin/ld: /lib/x86_64-linux-gnu/libXext.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Signed-off-by: Sergey Senozhatsky <senozhatsky@chromium.org>